# Generated by Django 5.1.5 on 2025-02-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaApp.pizzacheese'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_crust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaApp.pizzacrust'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaApp.pizzasauce'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaApp.pizzasize'),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(to='PizzaApp.pizzatopping'),
        ),
    ]
