# Generated by Django 5.1.5 on 2025-02-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0003_order_card_cvv_order_card_expiry_order_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_name',
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry_date',
            field=models.CharField(default='01/23', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pizzatopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=5),
        ),
    ]
