# Generated by Django 5.1.5 on 2025-02-10 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0004_remove_order_card_expiry_remove_order_delivery_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_expiry_date',
            field=models.CharField(default='00/00', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_cheese',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.pizzacheese'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_crust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.pizzacrust'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_sauce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.pizzasauce'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.pizzasize'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='PizzaApp.pizzatopping'),
        ),
        migrations.AlterField(
            model_name='pizzacheese',
            name='name',
            field=models.CharField(default='Mozzarella', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzacrust',
            name='name',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzasauce',
            name='name',
            field=models.CharField(default='Tomato', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pizzatopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
