# Generated by Django 5.1.5 on 2025-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatopping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toppings_images/'),
        ),
    ]
